services:
  ruvents_doctrine.mapping.loader.annotation:
    class: Ruvents\DoctrineBundle\Mapping\Loader\AnnotationLoader
    arguments:
      - '@annotation_reader'

  ruvents_doctrine.mapping.factory:
    class: Ruvents\DoctrineBundle\Mapping\Factory\ClassMetadataFactory
    arguments:
      - '@ruvents_doctrine.mapping.loader.annotation'

  ruvents_doctrine.translator:
    class: Ruvents\DoctrineBundle\Translator
    arguments:
      - '@ruvents_doctrine.mapping.factory'
      - []

  ruvents_doctrine.doctrine.event_listener.translatable:
    class: Ruvents\DoctrineBundle\Doctrine\TranslatableListener
    arguments:
      - '@ruvents_doctrine.translator'
    tags:
      - { name: doctrine.event_subscriber }

  ruvents_doctrine.event_listener.translatable_request:
    class: Ruvents\DoctrineBundle\EventListener\TranslatableRequestListener
    arguments:
      - '@ruvents_doctrine.doctrine.event_listener.translatable'
    tags:
      - { name: kernel.event_listener, event: kernel.request }
