services:
  ruvents_doctrine.translator:
    class: Ruvents\DoctrineBundle\Translator
    arguments:
      - '@ruvents_doctrine.mapping.factory'
      - []

  ruvents_doctrine.doctrine.event_listener.translatable:
    class: Ruvents\DoctrineBundle\Doctrine\TranslatableListener
    arguments:
      - '@ruvents_doctrine.translator'
    tags:
      - { name: doctrine.event_subscriber }

  ruvents_doctrine.event_listener.translatable_request:
    class: Ruvents\DoctrineBundle\EventListener\TranslatableRequestListener
    arguments:
      - '@ruvents_doctrine.doctrine.event_listener.translatable'
    tags:
      - { name: kernel.event_listener, event: kernel.request }
